# Generated by Django 3.1.7 on 2021-02-24 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0002_auto_20210224_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.estudiante'),
        ),
    ]
